---

- name: Install ruby build dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev

- include: ruby/rbenv.yml tags=rbenv
  become_user: "{{ default_user }}"

- include: ruby/mri.yml tags=mri
  become_user: "{{ default_user }}"

# TODO: Also install Rubinius or JRuby?
