---

- name: Create repo directory
  file: path=/home/git/{{ blog_repo_dir }} state=directory
    owner=git group=git mode=755

- name: Create bare repo
  command: git init --bare chdir=/home/git/{{ blog_repo_dir }}
    creates=/home/git/{{ blog_repo_dir }}/HEAD
  become_user: git

- name: Create a coleslaw checkout
  git: repo=git://github.com/kingcons/coleslaw.git
    dest=/home/git/quicklisp/local-projects/coleslaw
    accept_hostkey=yes
  become_user: git

- name: Ensure post-receive hook is in bare repo
  shell: rsync -ci /home/git/quicklisp/local-projects/coleslaw/examples/example.post-receive /home/git/improvedmeans.git/hooks/post-receive
    creates=/home/git/improvedmeans.git/hooks/post-receive
  register: rsync_result
  changed_when: "rsync_result.stdout != ''"

- name: Make the post-receive hook executable
  file: path=/home/git/{{ blog_repo_dir }}/hooks/post-receive
    owner=git group=git mode=755

- name: Copy the coleslawrc file into place
  template: src=coleslaw.j2 dest=/home/git/.coleslawrc

- name: Make blog html dir
  file: path=/srv/www/{{ blog_domain }} owner=git group=www-data mode=755
    state=directory

- name: Make blog log dir
  file: path=/var/log/nginx/{{ blog_domain }} mode=755 state=directory

- name: Add an nginx template for the blog
  template: src=nginx.j2 dest=/etc/nginx/conf.d/{{ blog_domain }}.conf
  notify: restart nginx
