---

- name: Install git packages
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - git-sh

- name: Create git user
  user: name=git state=present # TODO: use shell=git-shell?

- name: Add pubkey to git user authorized_keys
  authorized_key: user=git
    key="{{ lookup('file', '/home/redline/.ssh/id_rsa.pub') }}"
