---

### basics
domain: kingcons.io
email_user: brit
admin_email: "{{ email_user }}@{{ domain }}"

default_user: cons
default_shell: /bin/bash
default_pass: todo
default_build_dir: /home/{{ default_user }}/bin/builds

ssh_allowed_users:
  - "{{ default_user }}"
  - deploy
  - git

ssh_local_pubkey_path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

### and SSL is important, especially these days
ssl_key_path: /etc/ssl/private/wildcard_private.key
ssl_cert_path: /etc/ssl/certs/wildcard_public.crt

### everybody loves coleslaw
blog_repo_dir: improvedmeans.git
blog_deploy_dir: /srv/www/blog.{{ domain }}
blog_author: Brit Butler
blog_disqus_shortname: clockworkwebdevelopment
blog_analytics_code: UA-37659929-1
blog_title: Improved Means for Achieving Deteriorated Ends

### miscellaneous database settings
pg_version: 9.4
db_admin_pass: todo

### gotta have that email
mail_server_hostname: "{{ domain }}"
db_mail_user: postmaster
db_mail_pass: todo
db_mail_database: postbox

### virtual mail users/aliases/domains
vmail_users: todo
## Format for entries is:
# - account: "{{ admin_email }}"
#   domain: "{{ domain }}"
#   password_hash: foo
#   domain_pk_id: 1

vmail_aliases:
  - source: "root@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "admin@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "postmaster@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "webmaster@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "abuse@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1

vmail_domains:
  - name: "{{ domain }}"
    pk_id: 1

### you live on irc, right? gotta have a bouncer...
znc_version: 1.4
znc_user: redline
irc_nick: KingCons
irc_legacy_nick: redline6561
irc_real_name: Brit Butler
irc_timezone: America/New_York
irc_password_hash: todo
irc_password_salt: todo

# you know what's awesome? self-hosted cloud radio
s3fs_version: 1.79
nodejs_version: v0.12.7
s3_access_key: todo
s3_secret_key: todo
s3_mountpoints: todo
# mountpoint should be of the form: - { path: /foo, bucket: foo.bar }
radio_users: todo

# Add a user for mediagoblin
mediagoblin_user: mediagoblin
db_media_database: mediagoblin
media_users: todo
## Format for entries is:
# - { email: "foo@bar.com", user: "baz", pass: "quux" }
