---

# basics
domain: kingcons.io
admin_email: todo
default_user: cons
default_shell: /bin/bash
default_pass: todo

ssh_allowed_users:
  - "{{ default_user }}"
  - deploy
  - git

# everybody loves coleslaw
blog_repo_dir: improvedmeans.git
blog_deploy_dir: /srv/www/blog.{{ domain }}
blog_author: Brit Butler
blog_disqus_shortname: clockworkwebdevelopment
blog_analytics_code: UA-37659929-1
blog_title: Improved Means for Achieving Deteriorated Ends

# miscellaneous database settings
db_admin_pass: todo

# gotta have that email
db_mail_user: todo
db_mail_pass: todo
db_mail_database: postbox
