---

- name: Install necessary system packages
  apt: pkg=php5-fpm state=present

- name: Get latest shaarli version
  git: repo=git://github.com/sebsauvage/Shaarli.git
    dest=/srv/www/trace.kingcons.io
    accept_hostkey=yes force=yes

- name: Fix directory permissions
  file: state=directory path=/srv/www/trace.kingcons.io
    owner=www-data group=www-data mode=770 recurse=yes

- name: Make shaarli log dir
  file: path=/var/log/nginx/trace.{{ domain }} mode=755 state=directory

- name: Add an nginx template for shaarli
  template: src=nginx.j2 dest=/etc/nginx/conf.d/trace.kingcons.io.conf
  notify: restart nginx
