---

- hosts: newcons
  user: deploy
  become: yes
  vars_files:
    - vars/newcons.yml
    - vars/private.yml
  roles:
    - { role: common, tags: ['common'] }
    - { role: webserver, tags: ['web'] }
    - { role: blog, tags: ['blog'] }
    #- { role: mailserver, tags: ['mail'] }
    #- { role: bookmarks, tags: ['bookmarks'] }
    #- { role: bouncer, tags: ['irc'] }
    #- { role: radio, tags: ['radio'] }
    #- { role: mediaserver, tags: ['media'] }
    #- { role: redlinernotes, tags: ['redlinernotes'] }
    #- { role: webmail, tags: ['webmail'] }
